
# identity
username: kyshel  # meta-author, logo Button, post author, aside, footer
github_username: kyshel 
# remember about.md has id-info

# site-info
title: Kyshel - Hit the lights
email: 
description: >- # this means to ignore newlines
  Kyshel's blog
  Kyshel.me
  kyshel github


# url-info
footer_url: https://kyshel.com
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# edit button
repo_url: https://github.com/kyshel/kyshel.github.io
branch: master





# Build settings
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
# theme: minima
# highlighter: none # rouge if not set
plugins:
  - jekyll-feed

# paginate
plugins: [jekyll-paginate]
paginate: 10

# jquery_tag_cloud
tags_path: tags


defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
