# Site settings
title: Kyshel
description: "I need another story."
#url: "http://kyshel.me"




# Secondary Parameters
baseurl: ""
header_img: "/lib/img/pies.jpg"
headercolor: "#FFFFFF"
#logo: logo.png

# Pages
include: ['pages']


# Tertiary Parameters
github_username:  kyshel
#project_repository: project-pages
#disqus_shortname: project-pages
#g-analytics: UA-75881392-1
#altmetric: true

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
#highlighter: rouge
#permalink: pretty
paginate: 10
#exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.jpg"
